spring.application.name=employeeportal
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/employee_portal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
springdoc.swagger-ui.path=/swagger-ui.html
spring.security.user.name=Sriman
spring.security.user.password=Dikilona
